# Generated by Django 3.0.5 on 2020-05-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='asset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
    ]
