# Generated by Django 3.0.5 on 2020-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_activity_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
