# Generated by Django 3.0.5 on 2020-05-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20200507_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
    ]
