# Generated by Django 3.0.5 on 2020-05-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset'),
        ('logistics', '0004_remove_activity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='fromStation',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='toStation',
        ),
        migrations.AddField(
            model_name='activity',
            name='station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='asset.Station'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
    ]
